Create inst merge
Software-Projekt-Thiel-2020/Frontend pull request #102
Opened 2020-07-28 18:41 UTC by xGurke

An sich ist die Seite fertig.
Verbesserungsvorschläge:
- [V-Card (das weiße) schmaler machen]
- ["Institution Erstellen" Button ist nicht centered (sieht man bei schmaler Seite)]
- [Long/Latitude mit Map syncen, bisher nur Map-->coords aber nicht coords-->Map]
- ggf. Ortssuche mit Postleitzahl + Stadtname ergänzen

2020-07-31 16:03 UTC, Alizame approved these changes

2020-07-31 22:45 UTC, dermodmaster requested changes
Bitte Discussions lesen, hab noch Kleinigkeiten :)

2020-07-31 22:45 UTC, dermodmaster commented on src/components/pages/InstitutionEditieren.vue
> +      <div v-if="!gotResponse || items.length === 0">
Das wird schon angezeigt kurz nachdem die Seite geladen hat ob wohl wir noch gar nicht wissen ob der Nutzer wirklich keine Institutionen hat.
Am besten diese Meldung erst anzeigen, wenn wir auch eine Antwort von der API haben und wissen, dass es keine gibt.

2020-07-31 22:45 UTC, dermodmaster commented on src/components/pages/Institution.vue
> +        headers.website = this.website;
sollte das nicht eher **webpage** sein

2020-07-31 22:45 UTC, dermodmaster commented on src/components/pages/Institution.vue
> +        headers.website = this.website;
?

2020-07-31 22:45 UTC, dermodmaster commented on src/components/pages/Institution.vue
> +        headers.website = this.website;
also headers.webpage

2020-07-31 23:12 UTC, xGurke commented on src/components/pages/Institution.vue
> +        headers.website = this.website;
yeah

2020-07-31 23:16 UTC, xGurke commented on src/components/pages/InstitutionEditieren.vue
> +      <div v-if="!gotResponse || items.length === 0">
bug wurde gefixt

2020-08-01 18:26 UTC, dermodmaster approved these changes

2020-08-01 18:27 UTC, merged