Spendenbutton bei 0 Eth disabled
Software-Projekt-Thiel-2020/Frontend pull request #139
Opened 2020-08-03 23:15 UTC by CodingJosh42

siehe Titel

2020-08-03 23:43 UTC, Alizame commented on src/components/pages/Project.vue
> +      }
```suggestion
      this.donationDisabled = this.donationValue <= 0;
``
?

2020-08-03 23:44 UTC, Alizame commented on src/components/pages/Project.vue
> +      }
ungetestet

2020-08-04 00:09 UTC, CodingJosh42 commented on src/components/pages/Project.vue
> +      }
Ich verstehe gerade nicht was du meinst? Wenns kleiner 0 ist soll es auch disabled sein. (Man kann ja sowieso keine negativen Zahlen eingeben also vielleicht unnötig)

2020-08-04 00:58 UTC, xGurke commented on src/components/pages/Project.vue
> +      }
Er meint, dass man sich das if-else sparen kann, da man direkt nen Boolean zuweisen kann.

2020-08-04 01:02 UTC, CodingJosh42 commented on src/components/pages/Project.vue
> +      }
Achso ja gut, das ist jetzt Geschmackssache. ABer kann ich machen

2020-08-04 09:08 UTC, dermodmaster requested changes

2020-08-04 09:08 UTC, dermodmaster commented on src/components/pages/Project.vue
> +                      :disabled="donationDisabled"
ist ein :disabled="this.donationValue <= 0" nicht schöner?

2020-08-04 09:08 UTC, dermodmaster commented on src/components/pages/Project.vue
> +                      :disabled="donationDisabled"
der rest würde dann wegfallen

2020-08-04 12:07 UTC, Alizame approved these changes

2020-08-04 12:13 UTC, merged