Task/spenden
Software-Projekt-Thiel-2020/Frontend pull request #49
Opened 2020-06-09 21:03 UTC by dermodmaster

2020-06-09 21:28 UTC, Alizame commented
linter

2020-06-11 19:37 UTC, Alizame requested changes

2020-06-11 19:37 UTC, Alizame commented on src/components/pages/Spenden.vue
> +                </h2>
man könnte h2 entfernen + nen style hinzufügen wo dann font-size & text-align drin ist.

2020-06-11 19:37 UTC, Alizame commented on src/components/pages/Spenden.vue
> +      });
sollte gotResponse nicht nur bei erfolg gesetzt werden? asking for a friend

2020-06-11 19:49 UTC, dermodmaster commented on src/components/pages/Spenden.vue
> +                </h2>
Ich hoffe du bist jetzt glücklich! 🥇

2020-06-11 19:50 UTC, Alizame approved these changes

2020-06-11 19:50 UTC, Alizame approved these changes

2020-06-11 19:51 UTC, merged