Profil merge
Software-Projekt-Thiel-2020/Frontend pull request #60
Opened 2020-06-16 09:37 UTC by xGurke

Profil Daten werden per API geladen. Review und ggf. mergen, danke.

2020-06-16 10:17 UTC, xGurke commented
Es tritt noch ein Fehler mit window.user auf, Noch nicht mergen.

2020-06-16 14:35 UTC, xGurke commented
Fehler wurde behoben und eine extra Fehlermeldung wird nun angezeigt, wenn die API keine Daten aber Status 200 zurückgibt.
Der Branch sollte nun wieder bereit fürs mergen sein.

2020-06-17 15:31 UTC, xGurke commented
resolves #54 #59

2020-06-18 17:16 UTC, Alizame requested changes

2020-06-18 17:16 UTC, Alizame commented on src/components/pages/BenutzerProfil.vue
> +            this.loadData();
```suggestion
            this.loadData();
            this.reset();
```

2020-06-18 17:36 UTC, Alizame approved these changes

2020-06-18 18:51 UTC, dermodmaster approved these changes
Great job!

2020-06-18 18:51 UTC, merged