created ProjektAnlegen.vue
Software-Projekt-Thiel-2020/Frontend pull request #72
Opened 2020-06-23 01:34 UTC by Sascha-Ruehrup

required Felder bis auf authToken sind vorhanden. bei dem Authtoken weiß ich nicht, wie ich da was mit machen kann.

2020-06-25 15:50 UTC, Alizame commented
snackbar wie beim registrieren (siehe https://vuetifyjs.com/en/components/snackbars/ ) statt console.log

2020-06-25 21:11 UTC, dermodmaster commented
Was @Alizame sagt, wäre gut :)

2020-06-25 21:12 UTC, dermodmaster requested changes
Was @Alizame sagt, wäre gut :)

2020-06-29 16:45 UTC, Sascha-Ruehrup commented
hab jetzt die console.logs ersetzt und snackbars eingebaut. konnte sie aktuell nicht testen.

2020-06-29 19:45 UTC, merged