Filterfunktion nach Name hinzugefügt
Software-Projekt-Thiel-2020/Frontend pull request #79
Opened 2020-06-26 16:54 UTC by xGurke

Man kann jetzt die Institutionen nach Namen sortieren. #52

2020-06-26 17:29 UTC, xGurke commented
Anregungen und Änderungsvorschläge sind wilkommen :)
Ich schiebe das Ticket #79 wieder auf "on-hold" da es noch nicht klar ist, wir der Filter nach dem Ort aussehen soll.

2020-06-26 17:29 UTC, Alizame commented on src/components/pages/Spenden.vue
> +          v-for="index in resultList.length"
was isn das hier für'n plan?

2020-06-26 17:29 UTC, Alizame commented on src/components/pages/Spenden.vue
> +    resultList: [],
warum nicht items weiterverwenden?

2020-06-26 17:37 UTC, xGurke commented on src/components/pages/Spenden.vue
> +    resultList: [],
items brauche ich, wenn ich einen Filter zurücksetzte, dass die Institution wieder angezeigt werden

2020-06-26 17:37 UTC, xGurke commented on src/components/pages/Spenden.vue
> +          v-for="index in resultList.length"
Macht keinen Sinn, stimmt

2020-06-26 17:51 UTC, Alizame approved these changes

2020-06-29 17:43 UTC, dermodmaster commented on src/components/pages/Spenden.vue
> +    lCodes: ['DE', 'PL', 'USA'],
Maybe eher Deutschland, Österreich, Schweiz? Weil Seite ist ja deutschsprachig :)

2020-06-29 17:46 UTC, dermodmaster commented on src/components/pages/Spenden.vue
> +    radius: 0,
Usability: Bitte einen Standardwert eintragen, den ein Benutzer wirklich interessieren könnte.. Vielleicht 10km, oder 25km aber nicht 0km

2020-06-29 17:49 UTC, dermodmaster requested changes
Angeforderte Änderungen siehe Discussions

2020-06-29 19:47 UTC, xGurke commented on src/components/pages/Spenden.vue
> +    lCodes: ['DE', 'PL', 'USA'],
Wurde verbessert

2020-06-29 19:48 UTC, xGurke commented on src/components/pages/Spenden.vue
> +    radius: 0,
Radius wird nun beim Aufruf nun auf 1 gesetzt, War auch eigentlich so geplant.

2020-06-29 21:26 UTC, xGurke commented
Nun werden Spendenprojekte geladen --> Suchfunktion ist hoffentlich schlussendlich fertig. Ein letzes mal reviewen und ggf mergen :)

2020-06-30 19:58 UTC, merged