Gutscheine anzeigen lassen und kaufen (Issue 42)
Software-Projekt-Thiel-2020/Frontend pull request #81
Opened 2020-06-27 19:27 UTC by CodingJosh42

Neue Komponente ProjectGutschein erstellt um einen Gutschein anzeigen zu lassen. Oben auf der Seite werden Infos zu der Institution angezeigt. Darunter werden die Gutscheine der Institution dargestellt. Bei jedem Gutschein wird der Titel, eine Beschreibung, der Preis (von Ether in Euro umgerechnet), die gültige Zeit in Jahren und die Anzahl der verkauften Gutscheine angezeigt. Gutscheine können nur von eingeloggten Usern gekauft werden.

2020-06-28 15:22 UTC, Alizame commented
es wäre denke ich ganz gut wenn man ein "visuelles feedback" bekommt wenn man auf kaufen drückt, das der kauf verarbeitet wird, sonst kann man denken der hat es nicht gecheckt.
Vuetify hat ja eine loading property

2020-06-28 15:23 UTC, Alizame commented
der website besuchen knopf leitet einen nicht auf die korrekte seite

2020-06-28 15:24 UTC, CodingJosh42 commented
Das mit der website liegt nicht an dem Button sondern an dem Link in der Datenbank

2020-06-28 15:26 UTC, Alizame commented
- backend liefert Wei und nicht Szabo, somit passt der Preis nicht

Bei mir leitet der mich auf "http://localhost:8080/www.msgraphic.com#/" weiter, das backend liefert aber nur "www.msgraphic.com"

2020-06-28 15:28 UTC, CodingJosh42 commented
Ja das liegt daran, dass bei dem Link "https" fehlt

2020-06-28 15:35 UTC, Alizame commented
`<a :href="'//' + project[0].webpage">`
try dis

2020-06-28 16:00 UTC, Alizame commented
du zeigst auch gutscheine an die man nicht mehr kaufen kann, du kannst das GET /vouchers/institution mit  dem Parameter "available=1" aufrufen

2020-06-28 16:29 UTC, CodingJosh42 commented
Also speichern wir jetzt doch Gutscheine ab die nicht mehr Verfügbar sind? Matthews meinte gestern nämlich dass wir das nicht machen

2020-06-28 16:33 UTC, Alizame commented
ja wir speichern die auch ab (müssen wir, sonst würden gekaufte gutscheine verloren gehen)
weiß nicht wie er darauf kam das dem nicht so wäre

2020-06-28 17:09 UTC, CodingJosh42 commented
Die Umrechnung war glaube ich sowieso falsch. Aber bist du dir sicher dass es Wei ist? Die Werte die man da zurückkriegt (z.B. 2000) sind nichtmal nen Cent Wert.

2020-06-28 17:10 UTC, Alizame commented
yep, das ist korrekt, das sind ja auch nur beispieldaten

2020-06-28 17:25 UTC, CodingJosh42 commented
Der letzte Commit sollte die Probleme gelöst haben. Bin mir nur bei der Umrechnung noch nicht ganz sicher ob das so jetzt richtig ist.

2020-06-28 18:59 UTC, dermodmaster requested changes
Hab noch kleine Verbesserungswünsche. Der Umrechnungsfaktor sieht mir richtig aus. Sieht cool aus.

2020-06-28 18:59 UTC, dermodmaster commented on src/components/pages/ProjectGutschein.vue
> +      <v-row v-if="vouchers.length==0">
Wäre cool, wenn das nur angezeigt wird, wenn auch wirklich keine Gutscheine vorhanden sind. Im Moment wird es eben auch während dem Ladevorgang angezeigt. :)

2020-06-28 18:59 UTC, dermodmaster commented on src/components/pages/ProjectGutschein.vue
> +            this.loading = false;
besser ein .finally(() => {}) benutzen um this.loading auf false zu setzen

2020-06-28 18:59 UTC, dermodmaster commented on src/components/pages/ProjectGutschein.vue
> +      <v-row v-if="vouchers.length==0">
Achso und während es lädt, wär optisches Feedback noch cool. z.B. kann man einen Spinner mit der Bedingung v-if="loading" einbauen.
https://vuetifyjs.com/en/components/progress-circular/

2020-06-29 20:00 UTC, dermodmaster approved these changes

2020-06-29 20:01 UTC, Alizame approved these changes

2020-06-29 20:17 UTC, merged